name: GitHub CI

on:
  push:
    branches: [ master, development ]

jobs:
  build:
    runs-on: macos-latest
    strategy:
      matrix:
        api-level: [29]

    steps:
      - name: checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: prep env.
        run: |
          set -x
          pwd
          touch local.properties
          echo "$GOOGLE_SERVICES" | base64 --decode > app/google-services.json
          ls -al

      - name: test + androidTest
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: ${{ matrix.api-level }}
          target: default
          script: ./gradlew testDebugUnitTest connectedDebugAndroidTest --stacktrace

      - name: combined coverage
        run: |
          set -x
          ./gradlew jacocoReport --stacktrace

      - name: coveralls
        env:
          COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
        run: |
          set -x
          ./gradlew coveralls

      - name: codecov
        run: |
          set -x
          bash <(curl -s https://codecov.io/bash)

      - name: static analysis I
        run: |
          set -x
          # ./gradlew ktlineformat
          ./gradlew ktlintCheck

      - name: static analysis II
        run: |
          set -x
          ./gradlew detekt

      - name: static analysis III
        run: |
          set -x
          ./gradlew lint pmd

      - name: sonarcloud
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          set -x
          ./gradlew sonarqube -Dsonar.host.url=https://sonarcloud.io -Dsonar.login="$SONAR_TOKEN" --stacktrace
