name: GitHub CI

on:
  push:
    branches: [ master, development ]

jobs:
  build:
    runs-on: macos-latest
    strategy:
      matrix:
        api-level: [23, 29]

    steps:
      - name: checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: prep env.
        env:
          GOOGLE_SERVICES: ${{ secrets.GOOGLE_SERVICES }}
        run: |
          set -x
          pwd
          touch local.properties
          echo "${GOOGLE_SERVICES}" | base64 -d > app/google-services.json
          ls -al app

      - name: test + androidTest
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: ${{ matrix.api-level }}
          target: default
          script: ./gradlew testDebugUnitTest connectedDebugAndroidTest --stacktrace

      - name: combined coverage
        run: |
          set -x
          ./gradlew jacocoReport --stacktrace

      - name: coveralls
        env:
          COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
        run: |
          set -x
          ./gradlew coveralls

      - name: codecov
        run: |
          set -x
          bash <(curl -s https://codecov.io/bash)

#      - name: static analysis - ktlint
#        run: |
#          set -x
#          # ./gradlew ktlintformat
#          ./gradlew ktlint

      - name: static analysis - detekt
        run: |
          set -x
          # ./gradlew detektBaseline
          ./gradlew detekt

      - name: static analysis - lint
        run: |
          set -x
          ./gradlew lint
